[project]
name = "beamforming-alg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "acoular>=24.7",
    "matplotlib>=3.9.4",
    "pyyaml>=6.0.2",
]
